"""Smoke test for train.py — end-to-end wiring, no GPU, no wandb.

Rationale (see doc/Train.md §9): a full unit-test suite for the training
loop is out of scope, but a smoke test that exercises

    config load → model+ema+ddp build → 3 training steps
    → 1 validation → 1 checkpoint → resume → 2 more steps

catches ~90% of the wiring bugs (off-by-one on --resume, wrong keys in
the checkpoint dict, mis-spelled config field, DDP-vs-single-process
control flow, etc.) that would otherwise only fail on a real GPU run.

This test:

*   builds a **tiny** DiT (`DiT_S_2` on 8x8 images, patch=2, 4 classes)
    over the four fixture PNGs under ``tests/fixtures/images/`` — the
    same fixtures used by :mod:`tests.test_dataset`;
*   runs on CPU with WORLD_SIZE=1 (no distributed init);
*   disables wandb (``mode: disabled``);
*   uses ``fid_ref_stats: null`` so the FID cache-build path is not
    exercised (the smoke test does exercise the *validation loop*, but
    the FID number is meaningless — that's what §8.1 warns about; we're
    just checking the wiring).

The test writes into ``tmp_path`` and cleans nothing up itself; pytest
handles that.
"""

from __future__ import annotations

import copy
import os
from pathlib import Path

import pytest
import torch
import yaml

# The fixture root and split match tests/test_dataset.py.
FIXTURES_ROOT = Path(__file__).resolve().parent / "fixtures"
FIXTURES_SPLIT = "images"
NUM_FIXTURE_CLASSES = 4


def _build_dataset_root(tmp_path: Path) -> Path:
    """Materialise a dataset root with a ``train/`` split under tmp_path.

    ``data.cifar10.CIFAR10Dataset`` requires the split directory to be
    named exactly ``train`` (that is what the training code passes).  The
    committed fixtures live under ``tests/fixtures/images/``; we shim
    that by symlinking (or copying, on filesystems where symlinks are
    forbidden) the fixture directory to ``<tmp_path>/data/train``.
    """
    root = tmp_path / "data"
    root.mkdir(parents=True, exist_ok=True)
    train_split = root / "train"
    src = FIXTURES_ROOT / FIXTURES_SPLIT
    try:
        os.symlink(src, train_split, target_is_directory=True)
    except OSError:
        # Fallback: copy the four tiny PNGs by hand.
        import shutil
        shutil.copytree(src, train_split)
    return root


def _build_smoke_configs(
    tmp_path: Path,
    run_name: str = "smoke",
    dataset_root: Path | None = None,
) -> tuple[Path, Path]:
    """Write a matched (train.yaml, model.yaml) pair into ``tmp_path``.

    Returns
    -------
    (train_yaml_path, model_yaml_path)
    """
    model_yaml = tmp_path / "model.yaml"
    train_yaml = tmp_path / "train.yaml"

    # Model: DiT_S_2 on 32x32x3 with 4 classes.
    #
    # 32x32 is the on-disk fixture size (see tests/fixtures/images/*.png,
    # generated by make_fixtures.py at 32x32).  With patch=2 that gives
    # 16*16 = 256 tokens — DiT_S_2 forward on CPU takes ~1s per step, so
    # a 3-step + resume-2-step smoke test finishes in well under a minute.
    model_yaml.write_text(yaml.safe_dump({
        "arch_name": "DiT_S_2",
        "input_size": 32,
        "in_channels": 3,
        "patch_size": 2,
        "num_classes": NUM_FIXTURE_CLASSES,
        "class_dropout_prob": 0.1,
    }))

    train_yaml.write_text(yaml.safe_dump({
        "model_config": "model.yaml",   # sibling in tmp_path

        "dataset": {
            "name": "cifar10",           # the CIFAR10Dataset class also handles the fixture
            "root": str(dataset_root) if dataset_root is not None else str(FIXTURES_ROOT),
            "download": False,
            "num_workers": 0,            # avoid worker-process spinup in the test
            "pin_memory": False,
            "augment": False,
        },

        "optim": {
            "name": "adamw",
            "lr": 1.0e-4,
            "betas": [0.9, 0.999],
            "weight_decay": 0.0,
            "grad_clip": 1.0,
            "warmup_steps": 1,           # exercise the warmup branch
            "lr_schedule": "constant",
        },

        "train": {
            "total_steps": 3,            # phase 1: 3 steps → ckpt → resume
            "batch_size_per_gpu": 2,     # 4 fixture images → 2 batches per epoch
            "grad_accum_steps": 1,
            "log_interval": 1,
            "ckpt_interval": 3,          # save at step 3
            "seed": 0,
            "amp_dtype": "fp32",         # bf16 requires CUDA
        },

        "ema": {
            "decays": [0.99],            # single fast-tracking EMA
        },

        "guidance": {
            "null_class_id": NUM_FIXTURE_CLASSES,
        },

        "validation": {
            "interval": 3,               # validate exactly once, at step 3
            "num_samples": 4,
            "batch_size_per_gpu": 4,     # single-chunk here; chunk-invariance
                                         # is exercised by its own dedicated test
                                         # (see test_run_validation_chunk_invariant).
            "visual_log_count": 4,
            "guidance_scales": [1.0],
            "metrics": {
                "fid": False,             # skip FID (needs Inception-v3 download)
                "inception_score": False,
            },
            "fid_ref_stats": None,
            "sampler": {"num_steps": 2},  # 2 Euler steps: fast, still exercises the loop
        },

        "logging": {
            "out_dir": str(tmp_path / "runs"),
            "run_name": run_name,
            "wandb": {
                "enabled": False,
                "project": "smoke",
                "entity": None,
                "token_path": str(tmp_path / "no_such_token"),
                "mode": "disabled",
            },
        },
    }))

    return train_yaml, model_yaml


# ---------------------------------------------------------------------------
# End-to-end run + resume
# ---------------------------------------------------------------------------

def test_train_smoke_end_to_end(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Run the complete train.py entry point in-process on CPU.

    Phase 1: run for 3 steps (matching total_steps), which triggers exactly
             one validation and one checkpoint save at step 3.
    Phase 2: bump total_steps to 5 in the same YAML, then re-invoke
             train.main() with --resume pointing at latest.pt.  The
             sampler must advance ``start_step`` correctly so training
             produces 2 more optimiser steps and finishes at step 5.
    """
    # Import lazily so the test file itself is importable even if train.py
    # has a top-level syntax error — which would then fail here loudly with
    # a real ImportError, rather than silently failing collection.
    import train as train_module

    # Pin to CPU regardless of host — the smoke test runs anywhere.
    monkeypatch.setattr(torch.cuda, "is_available", lambda: False)

    train_yaml, _model_yaml = _build_smoke_configs(
        tmp_path,
        run_name="smoke_run",
        dataset_root=_build_dataset_root(tmp_path),
    )

    # ---- Phase 1: fresh run, 3 steps ----
    train_module.main([
        "--config", str(train_yaml),
    ])

    run_dir = tmp_path / "runs" / "smoke_run"
    ckpt_dir = run_dir / "ckpt"
    latest = ckpt_dir / "latest.pt"

    assert ckpt_dir.is_dir(), f"expected checkpoint dir at {ckpt_dir}"
    saved = sorted(p for p in ckpt_dir.glob("step_*.pt"))
    assert saved, f"no step_*.pt written under {ckpt_dir}"
    assert latest.exists(), f"latest.pt symlink missing under {ckpt_dir}"

    # Load the checkpoint and verify its schema.
    payload = torch.load(latest, map_location="cpu", weights_only=False)
    for key in ("step", "model_state", "ema_states", "optim_state",
                "scheduler_state", "scaler_state", "rng_state",
                "config_yaml", "model_config_yaml", "git_sha", "version"):
        assert key in payload, f"checkpoint missing key {key!r}"
    assert payload["step"] == 3, f"expected step=3, got {payload['step']}"
    assert payload["version"] == train_module.CHECKPOINT_VERSION
    assert set(payload["ema_states"].keys()) == {"ema_0.99"}
    assert payload["scaler_state"] is None    # fp32 mode → no scaler

    # Check that the validation grid PNG landed on disk.
    grids = list((run_dir / "samples").glob("step*.png"))
    assert grids, f"expected at least one validation grid under {run_dir/'samples'}"

    # Snapshot the phase-1 online weights for the resume-continuity check.
    phase1_weights = copy.deepcopy(payload["model_state"])

    # ---- Phase 2: extend to total_steps=5 and resume ----
    raw = yaml.safe_load(train_yaml.read_text())
    raw["train"]["total_steps"] = 5
    raw["train"]["ckpt_interval"] = 5      # save at step 5
    raw["validation"]["interval"] = 5      # only validate at the end
    train_yaml.write_text(yaml.safe_dump(raw))

    train_module.main([
        "--config", str(train_yaml),
        "--resume", str(latest),
    ])

    # Phase 2 must have written a step_000000005.pt and updated latest.pt.
    payload2 = torch.load(latest, map_location="cpu", weights_only=False)
    assert payload2["step"] == 5, f"expected step=5 after resume, got {payload2['step']}"

    # Weights must have moved between phase 1 and phase 2 — otherwise the
    # resume path silently loaded a checkpoint but the loop never ran the
    # extra optimiser steps.
    any_moved = False
    for k, v in phase1_weights.items():
        if not torch.equal(v, payload2["model_state"][k]):
            any_moved = True
            break
    assert any_moved, "resume produced identical weights — extra steps did not train"


# ---------------------------------------------------------------------------
# Sub-component smoke tests (fast, CPU-only, no filesystem side-effects)
# ---------------------------------------------------------------------------

def test_resumable_sampler_skips_correct_number(tmp_path: Path) -> None:
    """ResumableDistributedSampler advances by ``start_step * bs`` samples."""
    import train as train_module

    dataset = list(range(20))               # 20-element dummy dataset

    sampler = train_module.ResumableDistributedSampler(
        dataset, num_replicas=1, rank=0, shuffle=False, seed=0, drop_last=True,
    )

    # A fresh sampler yields all 20 indices in order.
    fresh = list(iter(sampler))
    assert fresh == list(range(20)), fresh

    # After set_start_step(2, batch_size=4) → skip 2*4=8 samples.
    sampler.set_start_step(start_step=2, batch_size_per_rank=4)
    resumed = list(iter(sampler))
    assert resumed == list(range(8, 20)), resumed


def test_build_lr_scheduler_warmup(tmp_path: Path) -> None:
    """Linear warmup ramps 0 → 1 by warmup_steps, then holds at 1 for constant schedule."""
    import train as train_module
    from configs.schema import OptimConfig

    optim_cfg = OptimConfig(
        name="adamw", lr=1.0, betas=(0.9, 0.999),
        weight_decay=0.0, grad_clip=None,
        warmup_steps=4, lr_schedule="constant",
    )
    dummy = torch.nn.Linear(1, 1)
    opt = torch.optim.AdamW(dummy.parameters(), lr=optim_cfg.lr)
    sched = train_module.build_lr_scheduler(optim_cfg, total_steps=100, optimizer=opt)

    lrs = []
    for _ in range(6):
        opt.step()
        lrs.append(sched.get_last_lr()[0])
        sched.step()

    # LambdaLR calls lr_lambda(step) where step is the number of
    # sched.step() calls made so far — starting at 0.  With warmup=4
    # the ramp is 0/4, 1/4, 2/4, 3/4, 1.0, 1.0, ...
    assert lrs[0] == pytest.approx(0.0)
    assert lrs[1] == pytest.approx(0.25)
    assert lrs[2] == pytest.approx(0.5)
    assert lrs[3] == pytest.approx(0.75)
    assert lrs[4] == pytest.approx(1.0)
    assert lrs[5] == pytest.approx(1.0)


# ---------------------------------------------------------------------------
# Chunked-validation invariance regression
# ---------------------------------------------------------------------------

def _make_val_cfg(batch_size_per_gpu: int, num_samples: int = 6):
    """Build a minimal cfg-like object for run_validation.

    ``run_validation`` reads ``cfg.validation.*``, ``cfg.model.*``,
    ``cfg.ema.decays``, and ``cfg.train.seed``.  We construct only these
    attributes rather than a full TrainConfig, both to keep the fixture
    tiny and to make the test's requirements explicit.  If ``run_validation``
    grows a new dependency on ``cfg.<something>``, this helper will fail
    loudly with an AttributeError — which is the desired signal.
    """
    from types import SimpleNamespace

    return SimpleNamespace(
        validation=SimpleNamespace(
            num_samples=num_samples,
            batch_size_per_gpu=batch_size_per_gpu,
            visual_log_count=num_samples,      # log all of them → tensor easy to compare
            guidance_scales=(1.0,),
            metrics=SimpleNamespace(fid=False, inception_score=False),
            sampler=SimpleNamespace(num_steps=2),
            fid_ref_stats=None,
            interval=1,
        ),
        model=SimpleNamespace(
            arch_name="DiT_S_2",
            input_size=8,        # tiny — 8×8 with patch=2 → 16 tokens
            in_channels=3,
            patch_size=2,
            num_classes=NUM_FIXTURE_CLASSES,
            class_dropout_prob=0.1,
        ),
        ema=SimpleNamespace(decays=()),        # no EMA shadows: only the "online" tag runs
        train=SimpleNamespace(seed=0),
    )


def test_run_validation_chunk_invariant(tmp_path: Path,
                                         monkeypatch: pytest.MonkeyPatch) -> None:
    """Chunking must not change the images or metrics.

    Reproducibility contract (see ``run_validation`` docstring):

    *   Chunked ``randn``/``randint`` draws from a re-seeded ``val_gen``
        produce the same values as a single-shot draw of the same total
        size, sliced.
    *   The Euler sampler is a pure function of (weights, noise, labels,
        num_steps, guidance_scale), so it must produce identical outputs
        chunk-by-chunk vs. single-shot.
    *   ``save_image`` receives the concatenation of the leading ``k``
        images — which, given the two points above, must be bit-identical
        across chunkings.

    We assert this by intercepting ``train.save_image`` (patched at the
    module level, since ``run_validation`` uses the imported reference)
    and comparing the two captured tensors with ``torch.equal`` — no
    tolerance, no round-trip through PNG.
    """
    import train as train_module
    from configs.schema import ModelConfig

    monkeypatch.setattr(torch.cuda, "is_available", lambda: False)

    # Same weights across both runs: build once, snapshot state_dict.
    model_cfg = ModelConfig(
        arch_name="DiT_S_2",
        input_size=8,
        in_channels=3,
        patch_size=2,
        num_classes=NUM_FIXTURE_CLASSES,
        class_dropout_prob=0.1,
    )
    torch.manual_seed(0)
    net_ref = train_module.build_model(model_cfg)
    ref_state = copy.deepcopy(net_ref.state_dict())

    device = torch.device("cpu")
    run_dir = tmp_path

    def _run_once(batch_size_per_gpu: int) -> torch.Tensor:
        # Fresh network with the same weights each time — run_validation
        # uses copy.deepcopy on the state_dict internally, so mutation is
        # not a concern, but we play it safe.
        net = train_module.build_model(model_cfg)
        net.load_state_dict(ref_state)

        cfg_like = _make_val_cfg(batch_size_per_gpu, num_samples=6)

        captured: dict[str, torch.Tensor] = {}
        real_save = train_module.save_image

        def _capture_save_image(tensor, path, *args, **kwargs):
            # `tensor` here is the make_grid output (a single 3xHxW image).
            # We want the pre-grid batch for a clean comparison — but the
            # grid is a deterministic function of the batch, so equality
            # of the batch ⟺ equality of the grid.  Comparing the grid is
            # therefore sufficient and lets us keep the patch surface small.
            captured["grid"] = tensor.detach().clone()
            return real_save(tensor, path, *args, **kwargs)

        monkeypatch.setattr(train_module, "save_image", _capture_save_image)
        try:
            train_module.run_validation(
                step=0,
                online_net=net,
                ema_dict={},                       # no EMA copies for this test
                cfg=cfg_like,
                device=device,
                run_dir=run_dir,
                fid_metric=None,
                is_metric=None,
                wandb_run=None,
            )
        finally:
            monkeypatch.setattr(train_module, "save_image", real_save)

        assert "grid" in captured, "save_image was never called by run_validation"
        return captured["grid"]

    # num_samples=6 with:
    #   bs=6 → one chunk    (baseline, mirrors pre-chunking behaviour)
    #   bs=2 → three chunks (exercises chunked accumulation)
    #   bs=4 → two chunks with a short tail of size 2
    grid_single = _run_once(batch_size_per_gpu=6)
    grid_three  = _run_once(batch_size_per_gpu=2)
    grid_two    = _run_once(batch_size_per_gpu=4)

    # Exact equality — the noise is bit-identical across chunkings, and
    # euler_sample is a pure fp32 function on CPU.
    assert torch.equal(grid_single, grid_three), (
        "chunked (bs=2) validation grid differs from single-shot (bs=6): "
        "the chunk loop is not preserving the noise stream or the sampler."
    )
    assert torch.equal(grid_single, grid_two), (
        "chunked (bs=4, tail=2) validation grid differs from single-shot "
        "(bs=6): the short-tail chunk is not being handled correctly."
    )

